### ISSUE TITLE
no config?

### ISSUE THREAD

**Issue by jamesdwilson** [andylash/accounts-quickbooks#1]
What does it mean if it hits no config?
i am hitting this when i try to login

```
                                                                                                     // 20
```

  if (!config) {                                                                                         // 21
    console.log("no config");                                                                            // 22
    if (credentialRequestCompleteCallback) {                                                             // 23
      credentialRequestCompleteCallback(new ServiceConfiguration.ConfigError("Service not configured")); // 24
    }                                                                                                    // 25
    return;                                                                                              // 26
  }

**Comment by jamesdwilson** [comment]
the solution was

meteor add service-configuration

**Comment by andylash** [comment]
You're right.  I just added service-configuration to the dependencies and republished it.  Thanks for the catch.
